/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'shouhei' at '15/03/31 19:50' with Gradle 2.3
 *
 * @author shouhei, @date 15/03/31 19:50
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
