/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'shouhei' at '15/03/31 19:50' with Gradle 2.3
 *
 * @author shouhei, @date 15/03/31 19:50
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
